### ISSUE TITLE
Not able to bypass JSON issue

### ISSUE THREAD

**Issue by sohailansari2** [braathen/qlik-auth-net#2]
Hello, after successfully installing the Qlik Auth Net and JSON libraries, I am seeing the following issue when launching the Default or Simple aspx files in browser.

Could not load file or assembly 'Newtonsoft.Json' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Can you please help? Thank you.

![image](https://cloud.githubusercontent.com/assets/22328142/21648598/27bde4ee-d264-11e6-9f28-b66db78a28ef.png)

**Comment by braathen** [comment]
I currently don't have a Windows/Visual Studio environment to test with unfortunately. If you installed QlikAuthNet through NuGet the dependencies should be handled automatically. I guess there could be a version conflict or incompatibility going on here. When QlikAuthNet was published Newtonsoft.JSON was on v6.0.8 and it has now passed v9.x, you could try to force that package to be v6.0.8 instead and it might work better. Try this...

PM> Uninstall-Package Newtonsoft.Json -Force
PM> Install-Package Newtonsoft.Json -Version 6.0.8

**Comment by sohailansari2** [comment]
Rikard,


Thanks for your reply. You are right as this was the version conflict with Newtonsoft. I uninstalled and reinstalled the QlikAuthNet and the error went away.


Thank you,


________________________________

**Comment by braathen** [comment]
Cool! Thanks for letting me know. Closing this now.... cheers!
