### ISSUE TITLE
Found New Error Message

### ISSUE THREAD

**Issue by sohailansari2** [braathen/qlik-auth-net#3]
I am seeing Error 403 Forbidden message. Can you think of something to help here. Please take a look at screenshot.

Thank you,

![newerror](https://cloud.githubusercontent.com/assets/22328142/21743732/df43d2c0-d4cd-11e6-9cbd-f2a8bd33e88e.png)

**Comment by braathen** [comment]
Probably wrong certificate, the certificate is what is used as trust so basically it should be the only thing causing a 403. Did you export the client certificate from QMC, then importing it into the Certificate Store?

**Comment by sohailansari2** [comment]
Rikard, thanks for your reply.


I am testing this on the same machine i.e. QS and IIS are on the same machine. I have not exported the client certificate because the certificate got installed in the Certificate Store automatically after QS installation. Here is the screenshot. Do you think I still need to export certificate?


Thank you,



________________________________

**Comment by braathen** [comment]
Yes, try it... :) or look for the certificate called QlikClient.

**Comment by sohailansari2** [comment]
I have exported the Certificate out of QMC and then imported it into MMC as you have described in one of your PDF document. That created a duplicate certificate (screenshot attached).


The error message is not different as it says "Could not create SSL/TLS secure channel."(screenshot attached).


I am unable to find any certificate by the name of QlikClient. I have read that QlikClient certificate has been discontinued with QS version 3.0


Thanks,



________________________________

**Comment by sohailansari2** [comment]
Rikard, I got it working now. Thanks for your advice. It was in fact "QlikClient" certificate that was missing. The "QlikClient" certificate got imported into MMC when I imported the "Client" certificate. And your code started working.


However, I had to make a minor change in your code and recompile it to make it work i.e.


On QlikAuthNet.cs file, I had to change line number 43


CertificateLocation = StoreLocation.CurrentUser;

to

CertificateLocation = StoreLocation.LocalMachine;


Thank you for all your help.


Regards,

Sohail Ansari






________________________________

**Comment by braathen** [comment]
I was under the impression the CertificateLocation was configurable as options, maybe I need to have a look at that some day, it was contributed by someone a while ago. Anyway, glad that you got it working, good job! Closing this now...
