### ISSUE TITLE
Help Please!

### ISSUE THREAD

**Issue by andywhitfield568** [braathen/qlik-auth-net#6]
Hi Rikkard,

This is a long shot. I work for CACI in the UK we are a Qlik Partner. We have a client who has gone it alone and developed a ticketing module is asp.net, which they have eventually got working internally, but have now deployed it on IIS for external customer (PS I am not a developer) and it fails with:

504 Gateway timeout Gateway timeout exired while waiting for server response

![image](https://user-images.githubusercontent.com/18164645/35619478-186eb422-0676-11e8-8293-0d83ca72fcfd.png)

 The sent a code snippet and they are using QlikAuthNet so wonder if you could hopefully supply any pointers.

Thanks in advance

Andy

**Comment by andywhitfield568** [comment]
Here's the code snippet from there prototype stage:

![image](https://user-images.githubusercontent.com/18164645/35619674-9c2d1858-0676-11e8-8595-c9c90a413188.png)

**Comment by braathen** [comment]
The way the module is intended to be used is as a Custom authentication module configured through the Virtual Proxy in QMC. No hardcoded paths or urls should be needed. This example seems to be using internal servernames. I would just get rid of everything and start from scratch, creating a listening URL, configure this in QMC and go from there.

**Comment by andywhitfield568** [comment]
Wow, that was quick! Would it be OK if I got the end user developer to contact  you directly?

**Comment by braathen** [comment]
Sure, but the above is my recommendation and key to make it work, keep it simple.

**Comment by FaisalMughal81** [comment]
Hi Braathen, thanks for your suggestions. 
We've removed our QlikSense setup, and now we're in the process of setting it up on another server, so once we're all set then I will try your recommendations and will let you know.
Many Thanks!

**Comment by FaisalMughal81** [comment]
Hi Braathen,

I have tried as you suggested but still no luck! 

I have attached screenshots of code and QMC for your reference. 

[QlikSense-Net.zip](https://github.com/braathen/qlik-auth-net/files/1686653/QlikSense-Net.zip)

**Comment by braathen** [comment]
So, the error message you are seeing is coming from IIS, not Qlik Sense. The url also contains a ticket. This means that the ticket was successfully retrieved but the redirection URL is wrong, it's not going to the Qlik Sense server but to a webserver.

**Comment by andywhitfield568** [comment]
Hi Rikkard,

thank for the help so far, just recieved this back from Faisal:

As per Braathen’s suggestions, we removed server names/IPs but it didn’t make any difference. Updated Braathen’s blog with the details, and he responded it’s an IIS issue, but we disagree. 
Firstly, we have to provide port 8080 otherwise IIS won’t be able to understand/redirect the request to QlikSense. Secondly, we tried accessing QlikSense externally through HTTPS and IIS is redirecting to QlikSense Hub but with an error, which at least proves that we need to provide relevant ports.

Andy, we reckon we’ve only got the http URL wrong to access QlikSense.

I have tried below methods today:

Firstly, I applied below change to access the QlikSense Hub through HTTPS:
 

Externally, IIS is taking us to QlikSense Hub but throws below error:
![image](https://user-images.githubusercontent.com/18164645/35732648-2896a5ce-0812-11e8-81d1-7aa7f6de6b5b.png)

 

For above error, we found a thread on Qlik Community and opened all the ports and whitelisted IPs as suggested but no luck: https://community.qlik.com/thread/235051


Secondly, I tried accessing QlikSense with HTTP, but I get same Gateway Timeout error. 
 

Note: I also used only port with Virtual Proxy but no luck – (RedirectLink = ":8080/custom/hub?" + ticket;)

**Comment by braathen** [comment]
The 504 and 404 errors you are getting are coming from IIS.

The error message from Qlik Sense is usually caused by IP white listing. Can you provide me with screenshots of your entire QMC Virtual Proxy settings?

There still doesn't seem to be any custom authentication module configured. This module should be reachable form the outside as the user is being redirected there. If everything is done properly, redirectUrl will be received automatically from the proxy.

**Comment by andywhitfield568** [comment]
At last!
I’ve added BunzlRetail.com, and It finally works!!! 

However, it’s only working for HTTPS, and doesn’t like HTTP, but I think we can live with it for now.

Thanks for your help!

**Comment by braathen** [comment]
Nobody likes HTTP... :)

I'm glad you got it running, good work!
